### ISSUE TITLE
Create a configuration file

### ISSUE THREAD

**Issue by kcurtis25** [kcurtis25/number-puzzles#4]
There are some things (for instance install directory) which will need to change from install to install, but which we need the code to know about. 

In order to do this, we'll create a `config.json.example` file at the top level directory which contains the details. Then users can copy that to `config.json` on their on host (which'll be git ignored) to configure their own install. So far, only `install_directory` is needed.

```
{
        "install_directory": "/opt/number-puzzles"
}
```

We can then use the perl module `File::Slurp` to quickly read in the contents. 

Problem we have is a chicken-and-egg one. How do we specify where the config file is without the `install_directory` data that is in the file....

**Comment by kcurtis25** [comment]
cc @phowlin

**Comment by phowlin** [comment]
@kcurtis25 Suggest this issue is closed as the specific configuration parameter (install_directory) is no longer required. Could be established 'as needed' later. Alternatively, issue could be left open and file created containing only 'dummy' data so it could be filled as needed. Thoughts?

**Comment by kcurtis25** [comment]
Closed now that https://github.com/kcurtis25/number-puzzles/pull/5 is merged

**Comment by kcurtis25** [comment]
Yep. Close it. Given the small number of people, and the low focus on this (we have better things to do) let's ensure that the outstanding issues are only the things we plan to do in the short-ish term.

We can raise a more detailed issue later if we do actually need a configuration file.
